### ISSUE TITLE
'guestfs.h' file not found

### ISSUE THREAD

**Issue by pierrezurek** [zchee/docker-machine-xhyve#4] opened 2015-10-26 16:54 UTC
Hi,

When building on Mac OS X inside the folder ~/gopath/src/github.com/zchee/docker-machine-xhyve, I have the following error :

```
$ make
# ./scripts/static.sh godep go build -i -o ./bin/docker-machine-xhyve ./bin
godep go build -i -o ./bin/docker-machine-driver-xhyve ./bin
# libguestfs.org/guestfs
/usr/local/Cellar/libguestfs/1.31.7/lib/golang/src/libguestfs.org/guestfs/guestfs.go:30:10: fatal error: 'guestfs.h' file not found
#include "guestfs.h"
         ^
1 error generated.
godep: go exit status 2
make: *** [bin/docker-machine-driver-xhyve] Error 1
```

My GOPATH is :

```
$ echo $GOPATH
~/gopath:/usr/local//Cellar/libguestfs/1.31.7/lib/golang
```

I followed the README file, do you have any idea ?

Thanks,

Pierre

**Comment by zchee** [comment] 2015-10-27 03:44
Missed closed.
I will reply later :)

**Comment by zchee** [comment] 2015-10-27 04:04
@pierrezurek 
Try
```bash
ls -la /usr/local/Cellar/libguestfs/1.31.7/include/guestfs.h
# also
ls -la /usr/local/Cellar/libguestfs/1.31.7/include/guestfs.h
```

Result:
```bash
-rw-r--r--   1 zchee  admin  196312 Oct 23 02:19 guestfs.h
# also
lrwxr-xr-x  1 zchee  staff  45 Oct 26 22:30 /usr/local/include/guestfs.h -> ../Cellar/libguestfs/1.31.7/include/guestfs.h
```
That correct?

Next, `docker-machine-xhyve` use Go official package vendoring. `guestfs.go` included `vendor` directory.
So, `/usr/local/Cellar/libguestfs/1.31.7/lib/golang/src/libguestfs.org/guestfs/guestfs.go` is not needed.
See https://github.com/zchee/docker-machine-xhyve/blob/master/vendor/libguestfs.org/guestfs/guestfs.go

Go vendoring mecanisum implement Go version 1.5 or later.
If you use Go version 1.4 or previous, please upgrade Go 1.5.
And, `export $GO15VENDOREXPERIMENT=1`.
FYI, https://medium.com/@freeformz/go-1-5-s-vendor-experiment-fd3e830f52c3#.tsjv37dlc

After trying these, please comment again :)

**Comment by pierrezurek** [comment] 2015-10-27 10:21
Hi !

Thanks for your help. I followed your instructions :

```
$ go version
go version go1.5.1 darwin/amd64
$ ls -la /usr/local/include/guestfs.h
lrwxr-xr-x  1 admin  staff  45 26 oct 17:19 /usr/local/include/guestfs.h -> ../Cellar/libguestfs/1.31.7/include/guestfs.h
$ ls -la /usr/local/Cellar/libguestfs/1.31.7/include/guestfs.h
-rw-r--r--  1 admin  admin  196312 26 oct 17:15 /usr/local/Cellar/libguestfs/1.31.7/include/guestfs.h
$ export GOPATH=~/gopath
$ export GO15VENDOREXPERIMENT=1                                                                                                                                                  
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/admin/gopath"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.5.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.5.1/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

But the make step still failed :

```
$ make
# ./scripts/static.sh godep go build -i -o ./bin/docker-machine-xhyve ./bin
godep go build -i -o ./bin/docker-machine-driver-xhyve ./bin
# github.com/zchee/docker-machine-xhyve/vendor/libguestfs.org/guestfs
vendor/libguestfs.org/guestfs/guestfs.go:31:10: fatal error: 'guestfs.h' file not found
#include "guestfs.h"
         ^
1 error generated.
godep: go exit status 2
make: *** [bin/docker-machine-driver-xhyve] Error 1
```

I add to apply the following patch to the vendor/libguestfs.org/guestfs/guestfs.go file :

```
diff --git a/vendor/libguestfs.org/guestfs/guestfs.go b/vendor/libguestfs.org/guestfs/guestfs.go
index 078c5a1..3813789 100644
--- a/vendor/libguestfs.org/guestfs/guestfs.go
+++ b/vendor/libguestfs.org/guestfs/guestfs.go
@@ -23,9 +23,9 @@
 package guestfs
 
 /*
-#cgo CFLAGS:  -DGUESTFS_PRIVATE=1
+#cgo CFLAGS:  -DGUESTFS_PRIVATE=1 -I/usr/local/include
 // #cgo LDFLAGS: -undefined dynamic_lookup -lguestfs
-#cgo LDFLAGS: -lguestfs
+#cgo LDFLAGS: -L/usr/local/lib -lguestfs
 #include <stdio.h>
 #include <stdlib.h>
 #include "guestfs.h"
```

Then the build went fine :

```
$ make
# ./scripts/static.sh godep go build -i -o ./bin/docker-machine-xhyve ./bin
godep go build -i -o ./bin/docker-machine-driver-xhyve ./bin
sudo chown root:admin ./bin/docker-machine-driver-xhyve
Password:
sudo chmod u+s ./bin/docker-machine-driver-xhyve
```

Pierre

**Comment by zchee** [comment] 2015-10-27 10:35
@pierrezurek Oh! I was relieved.
but, I do not know why that flag is required.
Hmm...

If you have time, Would you tell me those commands result?
```bash
which clang
clang -x c -v -E /dev/null
pkg-config libguestfs --cflags --libs
export CC=$(xcrun -f clang) export CXX=$(xcrun -f clang++) && make
```

**Comment by pierrezurek** [comment] 2015-10-27 10:45
```
$ which clang
/usr/bin/clang
$ clang -x c -v -E /dev/null
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.10.0 -E -disable-free -disable-llvm-verifier -main-file-name null -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 242.2 -v -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -fdebug-compilation-dir /Users/admin/gopath/src/github.com/zchee/docker-machine-xhyve -ferror-limit 19 -fmessage-length 208 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.10.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c /dev/null
clang -cc1 version 6.1.0 based upon LLVM 3.6.0svn default target x86_64-apple-darwin14.5.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks (framework directory)
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 321 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2

$ pkg-config libguestfs --cflags --libs
-lguestfs 
```

After stashing my modifications I tried the following :

```
$ export CC=$(xcrun -f clang)
$ echo $CC
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
$ export CXX=$(xcrun -f clang++)
$ echo $CXX
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
$ make
# ./scripts/static.sh godep go build -i -o ./bin/docker-machine-xhyve ./bin
godep go build -i -o ./bin/docker-machine-driver-xhyve ./bin
# github.com/zchee/docker-machine-xhyve/vendor/libguestfs.org/guestfs
vendor/libguestfs.org/guestfs/guestfs.go:29:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
godep: go exit status 2
make: *** [bin/docker-machine-driver-xhyve] Error 1
```

**Comment by zchee** [comment] 2015-10-27 11:02
@pierrezurek Thanks information :)

Hmm...
My result,
```
> /usr/bin/clang -x c -v -E /dev/null

Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -main-file-name null -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 253.6 -v -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0 -fdebug-compilation-dir /Users/zchee/go/src/github.com/zchee/cgo/xpc -ferror-limit 19 -fmessage-length 230 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c /dev/null
clang -cc1 version 7.0.0 based upon LLVM 3.7.0svn default target x86_64-apple-darwin15.0.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 325 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2
```

I think the correct to be displayed `/usr/local/include` below the `#include <...> search starts here:`
Problem caused by different of Xcode version...?

BTW, It seems safe is better to put the include path to  `CFLAGS`, lib path to `LDFLAGS`.
I will fix Makefile.

Thanks good report!!

**Comment by zchee** [comment] 2015-10-27 11:08
@pierrezurek 
I will close issue after fix the Makefile.

**Comment by zchee** [comment] 2015-10-27 11:19
@pierrezurek Sorry!! If you do not mind, please further information :pray:

```bash
CGO_CFLAGS="-DGUESTFS_PRIVATE=1 -I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lguestfs" godep go build -i -o ./bin/docker-machine-driver-xhyve ./bin
```
Works fine?

**Comment by pierrezurek** [comment] 2015-10-27 14:31
Hi !

`CGO_CFLAGS="-DGUESTFS_PRIVATE=1 -I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lguestfs" godep go build -i -o ./bin/docker-machine-driver-xhyve ./bin` is working fine.

However, please note that subsequent calls to `godep go build -i -o ./bin/docker-machine-driver-xhyve ./bin` (with no `CGO_CFLAGS` nor `CGO_LDFLAGS` set) will produce the `./bin/docker-machine-driver-xhyve` file without any error. I had to use the `godep go build -a -i -o ./bin/docker-machine-driver-xhyve ./bin` command to get the 'guestfs.h' build error again. The `-a` flag means `force rebuilding of packages that are already up-to-date`. Also, the `-x` and `-work` flags produce a more verbose output which can be useful.

**Comment by zchee** [comment] 2015-10-29 14:09
Merged. close

Thanks :)

**Closed by zchee** 2015-10-29 14:09 UTC
