### ISSUE TITLE
docker-machine rm hangs

### ISSUE THREAD

**Issue by nathanleclaire** [zchee/docker-machine-xhyve#8] opened 2015-11-12 18:53 UTC
Not sure what's going on, but `rm` just hangs completely and never finishes on incomplete VMs.

**Comment by zchee** [comment] 2015-11-12 19:26
@nathanleclaire 
I have not been able yet implemented it.
Because there is still no way to know the state(running? stopped? deleted?) of xhyve vm.
Also not been able yet implemented `Stop()` and `GetState()`.

I am thinking the best way.
xhyve does not seem to implement a way to get the state of vm in official (HEAD).
but, If merge the https://github.com/mist64/xhyve/pull/67 PR, We might be able to get the state from tty.
Or, there is a method of `goxhyve` leaves a pid file.
I think there are many other methods.

I do not know Which is best, and I have not yet fully understand `Go`, `C` and `framework.Hypervisor`.

Which you will think the best?

**Comment by zchee** [comment] 2015-11-12 19:46
@nathanleclaire FYI, Caused by https://github.com/zchee/docker-machine-xhyve/blob/master/xhyve.go#L334
`docker-machine-xhyve` not been able to stop the vm.

`Stop()` expect `if s == state.Running` return `false`, but `GetState()` always returns `state.Running`
https://github.com/zchee/docker-machine-xhyve/blob/master/xhyve.go#L312-L316
https://github.com/zchee/docker-machine-xhyve/blob/master/xhyve.go#L164

**Comment by nathanleclaire** [comment] 2015-11-12 19:59
OK, I see.  Thanks for the clarification.

**Comment by zchee** [comment] 2015-11-22 12:35
Fixed on https://github.com/zchee/docker-machine-xhyve/commit/f6a4f3adc143ac9907dd36f073118ec9d6201654
Close.

**Closed by zchee** 2015-11-22 12:35 UTC
